### ISSUE TITLE
input focus styling jump

### ISSUE THREAD

**Issue by bariscc** [Kommunity-app/kommunity-frontend#111]
focusing text increases the border size and causes a jump.
![screencast-localhost-3000-2018 12 02-21-53-32](https://user-images.githubusercontent.com/13869331/49355898-6e33c980-f67e-11e8-8200-36493479559d.gif)
We can change styling from border to shadow to avoid this.

**Comment by mustaphaturhan** [comment]
or we can create "transparent" border to input on initial render. There is one more problem about input.

![input](https://user-images.githubusercontent.com/11398393/49426706-62492400-f7b2-11e8-8c3e-c60bff1e0d89.jpg)

Icon's height should be 100% just in case. Otherwise, it cannot be vertically centered.

**Comment by bariscc** [comment]
@mustaphaturhan I have noticed that height issue too. I gave it full-height to solve this. 
As a side effect, if we ever use an icon in textarea, it'll look like this:
![textarea](https://user-images.githubusercontent.com/13869331/49480355-4312bc80-f7db-11e8-8eb5-816e380ef13c.png)
(I think it looks ok)

**Comment by mustaphaturhan** [comment]
Using icon in textarea isn't common pattern I think. I haven't seen website that uses text area with icon before.
