### ISSUE TITLE
[frontend] prettier config

### ISSUE THREAD

**Issue by mustaphaturhan** [Kommunity-app/kommunity-frontend#144]
we have prettier in our devDependencies but haven't created a .prettierrc file yet. things can go wrong if vscode's prettier settings different than default prettier settings.

there is an example prettier config file. please write your suggestions.

```json
{
  "useTabs": false,
  "printWidth": 80,
  "tabWidth": 2,
  "singleQuote": true,
  "trailingComma": "all",
  "jsxBracketSameLine": false,
  "bracketSpacing": true,
  "arrowParens": "always"
}
```

**Comment by trkaplan** [comment]
Instead of giving just warnings, auto-formatting long lines is a good feature.
![image](https://user-images.githubusercontent.com/992897/49758129-43c1bc00-fccf-11e8-9b55-5197a55662fa.png)

If you check our current codebase, we have lots of long lines, or the short ones formatted manually after we got eslint warnings. (Personally, It feels like a chore each time I do this.)

Similar discussion: https://github.com/prettier/prettier-eslint/issues/101#issuecomment-313233479
